### ISSUE TITLE
Unable to install getting this error

### ISSUE THREAD

**Issue by asimashfaq** [LEXUGE/nixos#4]
warning: --- Large path -------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
dumping very large path (> 256 MiB); this may run out of memory
error: --- Error --------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------- nix
hash mismatch in fixed-output derivation '/nix/store/pgn9gj4nf2m28hwaw82j3bc35rvf20f3-LINUX.drv':
  specified: sha256-RSiJaXVQ2xLlvAgj6NntCAHj8gFA24lYIGEemr+E+dw=
     got:    sha256-qeHPYKGSD5jY6AwJNWFGRE9NRU0ueBG4/FU2NgBZPcs=

**Comment by LEXUGE** [comment]
Oh, yes. You may want to disable the wolfram engine when you are installing. The file is located at `src/jupyter.nix`. Change both enable to false and that's it.
